### ISSUE TITLE
Opera 12.50 (desktop, alpha) doesn't render http://detector.dmolsen.com/

### ISSUE THREAD

**Issue by brucelawson** [dmolsen/Detector#10] opened 2012-08-09 11:30 UTC
Opera 12.50 alpha (aka Opera Next http://www.opera.com/browser/next/) on desktop doesn't render http://detector.dmolsen.com/, whereas Opera 12.01 does. In Opera.Next, masking as Firefox makes it work. That's often indicative of UA detection at play.

Opera 12.50 simplifies the UA string (see http://my.opera.com/ODIN/blog/2012/08/03/a-hot-opera-12-50-summer-time-snapshot :)

Opera 12.50 will ship with a simplified UA string. Firstly, we have dropped the "U;" token, which signified that the browser provides crypto support that is stronger than what the "international" builds of Netscape offered circa 1995. The second change is removal of the language indicator. As an example, while the UA string for Opera 12.01 on Mac is currently
Opera/9.80 (Macintosh; Intel Mac OS X 10.8.0; U; en) Presto/2.10.289 Version/12.01

today's snapshot for Opera 12.50 on Mac shows
Opera/9.80 (Macintosh; Intel Mac OS X 10.8.0) Presto/2.12.363 Version/12.50

Both these changes correspond to similar changes in the IE, Firefox, Chrome and Safari browsers' UA strings."

Could this be the issue? (Or should I be looking in https://github.com/tobie/ua-parser)

(Later addition) just had a chat with Tobie on twitter and filing a bug against UA parser as he suggested.

**Comment by dmolsen** [comment] 2012-08-22 20:27
@brucelawson -

this isn't a problem with ua-parser. the browser gets appropriately classified at http://uaparser.dmolsen.com/. It actually appears to be a problem with the Modernizr test createelement-attrs. Detector tries to combine UA sniffing with feature-detection to build UA-specific browser profiles. The test that is failing for me (and therefore causing the white screen) is:

https://github.com/Modernizr/Modernizr/blob/master/feature-detects/dom-createElement-attrs.js

The error is "Unhandled DOMException: INVALID_CHARACTER_ERR." That particular test was scheduled for removal from Detector for v1 so now is as good a time as any to nuke it.

Sorry about that as well as the long delay in answering. Never got a notice. I'll leave this issue open until I update the tests.

**Comment by hallvors** [comment] 2012-08-27 07:35
It's actually not a problem with that test but rather with https://github.com/Modernizr/Modernizr/blob/master/feature-detects/websockets-binary.js which isn't try..catch'ed. However, the problem might be on Opera's side if other browsers handle this code without throwing. We'll look into that..

**Comment by hallvors** [comment] 2012-08-27 08:10
We'll fix this in Opera, feel free to close this issue. :)

**Comment by dmolsen** [comment] 2012-08-27 13:54
thanks, @hallvors :) sorry 'bout the red herring on create elems. I could have sworn that I got that error but I can't recreate it. i should have done some more legwork to see if that really was the cause. have a good day.

**Closed as completed by dmolsen** 2012-08-27 13:54 UTC
